export interface Inductee {
  name: string;
  slug: string;
  photo: string;
  year: number | null;
  category: "shooting" | "administrative" | "both" | null;
  bio: string | null;
  featured: boolean;
}

export const inductees: Inductee[] = [
  {
    name: "Hortense Wood",
    slug: "hortense-wood",
    photo: "/inductees/hortense-wood.jpg",
    year: 1986,
    category: "both",
    bio: "One of the most decorated female trapshooters in ATA history, Hortense Wood began her shooting career in Utah around 1940 and went on to claim 19 Utah women's state championships along with one doubles and one all-around title over the men. She placed on 24 women's ATA All-America teams — 20 of them first-team honors — and in 1970 became only the second woman in ATA history to be handicapped at 27 yards, the maximum distance. A trailblazer off the range as well, she served as president of the Salt Lake Gun Club from 1960 to 1962, becoming the first woman to head a major gun club in the country.",
    featured: false,
  },
  {
    name: "Pat Miller",
    slug: "pat-miller",
    photo: "/inductees/pat-miller.jpg",
    year: 1986,
    category: null,
    bio: "Pat Miller is recognized among the foundational figures of Utah trapshooting, honored as one of the early inductees in the Utah Trapshooting Hall of Fame for sustained contributions to the sport and competition within the state.",
    featured: false,
  },
  {
    name: "Sam Sharman",
    slug: "sam-sharman",
    photo: "/inductees/sam-sharman.jpg",
    year: 1997,
    category: "shooting",
    bio: "Sam Sharman was among Utah's early competitive trapshooters and a recognized figure in the formative years of organized trapshooting in the state. He competed at the Grand American level, finishing as runner-up in the 1921 Grand American Doubles Championship in a shootoff, demonstrating his standing among the nation's top guns of that era.",
    featured: false,
  },
  {
    name: "E.L. Ford",
    slug: "el-ford",
    photo: "/inductees/el-ford.jpg",
    year: 1997,
    category: null,
    bio: "E.L. Ford holds a place among the pioneering figures of Utah trapshooting, inducted into the Utah Trapshooting Hall of Fame for contributions to the sport's growth and competitive heritage in the state.",
    featured: false,
  },
  {
    name: "C.H. Reilly",
    slug: "ch-reilly",
    photo: "/inductees/ch-reilly.jpg",
    year: 1997,
    category: null,
    bio: "C.H. Reilly is honored in the Utah Trapshooting Hall of Fame among the sport's early contributors and competitors in the state, recognized for helping establish the competitive trapshooting tradition that continues in Utah today.",
    featured: false,
  },
  {
    name: "Gus Becker",
    slug: "gus-becker",
    photo: "/inductees/gus-becker.jpg",
    year: 1997,
    category: "both",
    bio: "Ogden's Gustav Becker was recognized during his era as one of the world's premier trapshooters, winning the ATA handicap championship of America and taking state titles including Utah State Champion (1916), St. Joe Valley Champion (1918), and Chesapeake Champion (1930). He served as president of the Ogden Gun Club for over thirty years and held vice-presidential roles in the ATA and the Western Trap Shooting Association, making him as influential an administrator as he was a competitor. Becker represented the United States as an Olympic-level shooter and was later honored in both the Utah Trapshooting Hall of Fame and the Utah Sports Hall of Fame.",
    featured: false,
  },
  {
    name: "Ron Sellers",
    slug: "ron-sellers",
    photo: "/inductees/ron-sellers.jpg",
    year: 1997,
    category: "administrative",
    bio: "Ronald Sellers of Bountiful, Utah, has dedicated himself to preserving and promoting the history of Utah trapshooting, serving as the director of the Utah Trapshooting Hall of Fame. A competitive shooter in his own right, he has been a steadfast ambassador for the sport, bringing a traveling trapshooting museum to state championship events to share the heritage of the game with the broader Utah shooting community.",
    featured: false,
  },
  {
    name: "Arvin Labrum",
    slug: "arvin-labrum",
    photo: "/inductees/arvin-labrum.jpg",
    year: 1998,
    category: "shooting",
    bio: "Arvin G. Labrum (1932–2017) of the Uintah Basin was a dedicated and accomplished trapshooter who earned numerous awards in singles and doubles competition throughout his career. Inducted into the Utah Trapshooting Hall of Fame in 2003, Labrum famously flew himself to competitions across the United States in his own Beechcraft Bonanza aircraft, piloting a course that combined his two great passions — the skies and the clay target field.",
    featured: false,
  },
  {
    name: "Ken Adamson",
    slug: "ken-adamson",
    photo: "/inductees/ken-adamson.jpg",
    year: 1998,
    category: null,
    bio: "Ken Adamson is recognized as one of Utah's distinguished contributors to the sport of trapshooting, honored among the inductees of the Utah State Trapshooting Association's Hall of Fame for a career of sustained competitive excellence and commitment to the sport within the state.",
    featured: false,
  },
  {
    name: "Ann Christie",
    slug: "ann-christie",
    photo: "/inductees/ann-christie.jpg",
    year: 1998,
    category: null,
    bio: "Ann Christie is honored as a trailblazer in Utah trapshooting, recognized among the inductees of the Utah State Trapshooting Association's Hall of Fame. Her induction reflects both competitive achievement and a meaningful contribution to the growth of the sport in Utah, particularly for women in the shooting sports community.",
    featured: false,
  },
  {
    name: "O.J. Coon",
    slug: "oj-coon",
    photo: "/inductees/oj-coon.jpg",
    year: 1998,
    category: null,
    bio: "O.J. Coon stands among the pioneer inductees of the Utah State Trapshooting Association's Hall of Fame, recognized for his early and lasting contributions to the sport of trapshooting in Utah. His place alongside the association's founding-era honorees reflects a role in establishing the competitive trapshooting tradition that continues in the state today.",
    featured: false,
  },
  {
    name: "Josephine Leavitt",
    slug: "josephine-leavitt",
    photo: "/inductees/josephine-leavitt.jpg",
    year: 1998,
    category: "shooting",
    bio: "Josephine \"Jody\" Leavitt Jorgensen (1927–2023) of Kaysville and later St. George, Utah, was a multi-sport competitor who distinguished herself as an accomplished trapshooter alongside careers in bowling and golf. She earned numerous awards and accolades throughout her long life, and her competitive spirit and longevity in the sport made her an enduring example for women trapshooters across the state.",
    featured: false,
  },
  {
    name: "John M. Browning",
    slug: "john-browning",
    photo: "/inductees/john-browning.jpg",
    year: 1999,
    category: "both",
    bio: "Born January 23, 1855, in Ogden, Utah, John Moses Browning is widely regarded as the greatest firearms inventor the world has ever known, holding 128 patents and designing weapons that ranged from single-shot rifles to the Auto-5 — the world's first semi-automatic shotgun and a mainstay of the trapshooting community for generations. A dedicated competitive shooter himself, Browning was a member of the celebrated \"Four B's\" live bird trapshooting team alongside his brother Matthew, Gus Becker, and A.P. Bigelow, and regularly tested his shotgun designs in competitions around Ogden. His genius transformed not only the firearms industry but the clay target sports that Utah trapshooters have competed in ever since. Browning passed away in 1926, leaving a legacy inseparable from the history of the sport in his home state.",
    featured: false,
  },
  {
    name: "Tom Lynott",
    slug: "tom-lynott",
    photo: "/inductees/tom-lynott.jpg",
    year: 1999,
    category: "shooting",
    bio: "Tom Lynott was one of Utah's most decorated competitive trapshooters of the mid-twentieth century, compiling an impressive record across Singles, Doubles, and High-Overall events spanning more than two decades. Among his notable achievements: a 200-straight in Singles at Salt Lake City in 1949, High Overall Average at the 1953 Rocky Mountain Oyster shoot, doubles titles in 1953, 1955, and 1961, and a 98 from the 27-yard line at the 1956 Calgary Canadian Championship. Renowned as much for his mentorship as his marksmanship, Lynott was inducted into both the Utah and the national Trapshooting Hall of Fame. A decorated World War II B-24 bombardier, he was also made an honorary member of the Shoshone Nation's \"High Chief Thundering Gun\" society.",
    featured: false,
  },
  {
    name: "Walter Langhorst",
    slug: "walt-langhorst",
    photo: "/inductees/walt-langhorst.jpg",
    year: 1999,
    category: null,
    bio: "Walter \"Walt\" Langhorst was a respected figure in Utah's trapshooting community whose contributions to the sport earned him a place among the state's most honored inductees in the Utah Trapshooting Hall of Fame.",
    featured: false,
  },
  {
    name: "Dean Hurd",
    slug: "dean-hurd",
    photo: "/inductees/dean-hurd.jpg",
    year: 2000,
    category: null,
    bio: "Dean Hurd was a recognized competitor and contributor to Utah trapshooting who earned induction into the Utah State Trapshooting Association's Hall of Fame for his accomplishments in the sport.",
    featured: false,
  },
  {
    name: "Randy Freston",
    slug: "randy-freston",
    photo: "/inductees/randy-freston.jpg",
    year: 2000,
    category: "both",
    bio: "Born September 20, 1945, in Roosevelt, Utah, Randy Lynn Freston rose to the highest levels of the sport, serving as President of the Amateur Trapshooting Association in 1989 — a testament to both his world-class shooting ability and his commitment to the governance and growth of trapshooting nationally. A licensed civil engineer who owned his own firm for 35 years, Freston spent much of his later career giving back to the next generation through the Scholastic Clay Target Program, helping introduce young shooters to the discipline he loved. He passed away on March 19, 2015, at the age of 69.",
    featured: false,
  },
  {
    name: "H. Barr Carlisle",
    slug: "h-barr-carlisle",
    photo: "/inductees/h-barr-carlisle.jpg",
    year: 2001,
    category: null,
    bio: "Harvey Barr Carlisle was a Salt Lake City trapshooter whose place in the Utah Trapshooting Hall of Fame reflects a life devoted to the sport during a formative era for organized trapshooting in the state.",
    featured: false,
  },
  {
    name: "Dale Amos",
    slug: "dale-amos",
    photo: "/inductees/dale-amos.jpg",
    year: 2001,
    category: "shooting",
    bio: "Dale Amos stands as one of Utah's most distinguished competitive trapshooters, holding the Utah State Trapshooting Association's record for the highest handicap average — a benchmark of sustained precision few competitors have approached. A long-tenured ATA registered shooter, Amos has accumulated tens of thousands of registered targets across all three disciplines and has been a central figure in Utah's competitive trapshooting community for decades.",
    featured: false,
  },
  {
    name: "Ron Christensen",
    slug: "ron-christensen",
    photo: "/inductees/ron-christensen.jpg",
    year: 2001,
    category: null,
    bio: "Ron Christensen was a fixture in Utah's competitive trapshooting community, known for his steady presence both on the firing line and behind the scenes at ATA-registered events. A member of a core group of Utah shooters who helped shape the state's trapshooting culture, Christensen competed at the registered level and maintained his connection to the sport throughout his career.",
    featured: false,
  },
  {
    name: "Doug Westenskow",
    slug: "doug-westenskow",
    photo: "/inductees/doug-westenskow.jpg",
    year: 2002,
    category: null,
    bio: "Doug Westenskow is recognized by the Utah State Trapshooting Association as a contributor of lasting significance to the sport in Utah, earning a place among the state's most honored competitors and supporters in the Hall of Fame.",
    featured: false,
  },
  {
    name: "Brent Epperson",
    slug: "brent-epperson",
    photo: "/inductees/brent-epperson.jpg",
    year: 2004,
    category: "both",
    bio: "Brent Epperson has served the sport of trapshooting at both the competitive and organizational levels throughout his career in Utah. He was appointed as the Utah State ATA Delegate to the Western Zone, representing the interests of Utah shooters within the national governing structure of the Amateur Trapshooting Association. As a competitor, Epperson earned recognition in veteran class competition, including a veteran division doubles title. His dual role as administrator and active shooter exemplifies the kind of dedication the Utah Hall of Fame honors.",
    featured: false,
  },
  {
    name: "Bill Hunter",
    slug: "bill-hunter",
    photo: "/inductees/bill-hunter.jpg",
    year: 2004,
    category: null,
    bio: "Bill Hunter is honored by the Utah State Trapshooting Association as one of the figures who helped build and sustain the sport within the state. His contributions — whether through competitive shooting, volunteer service, or community support at Utah gun clubs — left a lasting impression on the trapshooters who came up around him.",
    featured: false,
  },
  {
    name: "Jim Duke",
    slug: "jim-duke",
    photo: "/inductees/jim-duke.jpg",
    year: 2007,
    category: "both",
    bio: "Jimmy Ray Duke was the founding father of organized trapshooting in the Heber Valley, organizing some of the region's earliest informal shoots and playing a central role in establishing the Heber Valley Gun Club — an institution that endures to this day. A lifelong competitor, Duke registered more than 231,000 ATA targets across singles, handicap, and doubles, claiming Utah State titles in singles (1987) and handicap (1994) along with multiple veteran and senior veteran championships. In the words of those who honored him, \"without Jimmy, there would be no trapshooting in the Heber Valley.\" He continued competing into his nineties and passed away on June 30, 2022, leaving behind a community he helped build from the ground up.",
    featured: false,
  },
  {
    name: "Larry Mitchell",
    slug: "larry-mitchell",
    photo: "/inductees/larry-mitchell.jpg",
    year: 2009,
    category: null,
    bio: "Larry Mitchell is a recognized figure within the Utah trapshooting community, honored by the Utah State Trapshooting Association for his contributions to the sport in the state. His induction into the Utah Trapshooting Hall of Fame reflects a career and legacy deemed worthy of the sport's highest state honor.",
    featured: false,
  },
  {
    name: "Joe Sudbury Sr.",
    slug: "joe-sudbury-sr",
    photo: "/inductees/joe-sudbury-sr.jpg",
    year: 2012,
    category: "shooting",
    bio: "Joe Sudbury Sr. is one of Utah's most accomplished registered trapshooters, celebrated for a competitive career marked by consistency and longevity. At the 2017 Utah State Shoot, he won the Singles Championship outright with a 200 straight, remarkably having broken all 500 singles targets across the entire week of competition. He continued to compete at the highest level into his senior veteran years, earning ATA Senior Veteran Second Team All-American honors. His dedication to registered competition over multiple decades makes him one of the most respected names in Utah trapshooting.",
    featured: false,
  },
  {
    name: "Linda Nicholl",
    slug: "linda-nicholl",
    photo: "/inductees/linda-nicholl.jpg",
    year: 2010,
    category: null,
    bio: "Linda Nicholl is recognized among a select group of women who helped shape competitive trapshooting in Utah. Her induction into the Utah Trapshooting Hall of Fame speaks to a career of sustained participation and achievement within the state's shooting community, contributing to the growth of women's competition in registered ATA events.",
    featured: false,
  },
  {
    name: "Joe Mabey",
    slug: "joe-mabey",
    photo: "/inductees/joe-mabey.jpg",
    year: 2010,
    category: null,
    bio: "Joe Mabey is enshrined in the Utah Trapshooting Hall of Fame in recognition of his contributions to the sport within the state, reflecting a legacy of dedication to the trapshooting community that the association deemed worthy of permanent recognition.",
    featured: false,
  },
  {
    name: "Bill Salt",
    slug: "bill-salt",
    photo: "/inductees/bill-salt.jpg",
    year: 2012,
    category: "shooting",
    bio: "Bill Salt earned his place among Utah's trapshooting elite through sustained excellence at the national level, earning selection to the ATA All-American Men's First Team in 1962 — a distinction that placed him among the finest registered competitors in the country. Competing during an era when Utah trapshooting was still building its stature on the national stage, Salt's achievement brought recognition to the state association and served as a benchmark for future generations of Utah shooters.",
    featured: false,
  },
  {
    name: "Bob Spencer",
    slug: "bob-spencer",
    photo: "/inductees/bob-spencer.jpg",
    year: 2013,
    category: null,
    bio: "Bob Spencer is a Hall of Fame inductee of the Utah State Trapshooting Association, recognized for his contributions to the state's trapshooting community through competition, service, or both.",
    featured: false,
  },
  {
    name: "Gene Majers",
    slug: "gene-majers",
    photo: "/inductees/gene-majers.jpg",
    year: 2015,
    category: "shooting",
    bio: "Gene Majers is a Utah-based ATA competitor recognized for his performance in the veteran category of registered trapshooting and his longevity as a competitive shooter in the state. His induction into the Utah Trapshooting Hall of Fame honors a career of sustained dedication to the sport.",
    featured: false,
  },
  {
    name: "Stanley Jorgenson",
    slug: "stanley-jorgenson",
    photo: "/inductees/stanley-jorgenson.jpg",
    year: 2001,
    category: null,
    bio: "Stanley Jorgenson is honored in the Utah Trapshooting Hall of Fame for his contributions to the sport within the state of Utah.",
    featured: false,
  },
  {
    name: "Bill & LeeAnn Martin",
    slug: "bill-and-leeann-martin",
    photo: "/inductees/bill-and-leeann-martin.jpg",
    year: 2016,
    category: "both",
    bio: "Bill and LeeAnn Martin of Vernal, Utah took up the sport together in 1996, joining Bill's brother Pete and business partner Craig Hart at their home club, Vernal Rod & Gun Club, where they later helped expand the trapline to 13 fields and construct a new club building. A decorated competitor, Bill earned three Utah state titles (1997 singles, 2000 doubles, 2013 veteran), a Grand American singles trophy in 2007, and completed his ATA Grand Slam in 2005 after shooting over 357,000 registered targets across 21 states and Canada. The Martins are among the most generous benefactors in the history of the sport, contributing $1 million toward construction of the ATA Hall of Fame and Museum in Sparta, Illinois, and sponsoring multiple six-figure Grand American challenge events. Bill and LeeAnn were inducted into the ATA Hall of Fame in 2014 — the highest honor the sport can bestow. Bill passed away on May 26, 2025, at age 78 in Vernal, Utah.",
    featured: false,
  },
  {
    name: "Ardith Stitt",
    slug: "ardith-stitt",
    photo: "/inductees/ardith-stitt.jpg",
    year: 2019,
    category: "administrative",
    bio: "Ardith Stitt devoted more than two decades to building the future of Utah trapshooting through tireless work with its youth. Beginning around 2000 as a fundraiser for the SCTP program, she helped send as many as six squads per year to the Grand American, regularly producing top-10 national finishes, before becoming Utah's state coordinator for the ATA's AIM program. She is credited with successfully lobbying for trap shooting to be recognized as a high school letter sport in Utah — a landmark achievement for the state's young competitors. Over 18-plus years of service, Ardith shaped the competitive futures of countless Utah junior shooters.",
    featured: false,
  },
  {
    name: "Sharred Oaks",
    slug: "sharred-oaks",
    photo: "/inductees/sharred-oaks.jpg",
    year: 2019,
    category: "shooting",
    bio: "Sharred Oaks of Vernal, Utah is one of the most accomplished young trapshooters the state has ever produced, becoming the youngest inductee in the Utah Trapshooting Hall of Fame at just 19 years of age. A member of the Vernal Rod & Gun Club — the oldest private trapshooting club in Utah — Sharred posted a rare 100-straight in all three events at a single registered shoot and capped his ATA Grand Slam with a perfect 300×300 performance from the 27-yard line. At the 2017 Utah State Shoot he won both the all-around and high-over-all titles, and at the Grand American he claimed junior honors in the NRA Singles with a 200 and won the junior doubles championship with a perfect 100.",
    featured: false,
  },
  {
    name: "Joe Roach",
    slug: "joe-roach",
    photo: "/inductees/joe-roach.png",
    year: 2017,
    category: null,
    bio: null,
    featured: false,
  },
  {
    name: "Leslie (Ford) Hight",
    slug: "leslie-ford-hight",
    photo: "/inductees/leslie-ford-hight.jpg",
    year: 2016,
    category: "shooting",
    bio: "Leslie Ford Hight is a long-standing competitor in Utah's ATA trapshooting community, competing primarily through the Spanish Fork Gun Club. She has been recognized for sustained performance in women's competition, reflecting decades of consistent competitive excellence at the registered level.",
    featured: false,
  },
  {
    name: "Pam Wright",
    slug: "pam-wright",
    photo: "/inductees/pam-wright.jpg",
    year: 2026,
    category: null,
    bio: null,
    featured: true,
  },
  {
    name: "Pauline Deleeuw",
    slug: "pauline-deleeuw",
    photo: "/inductees/pauline-deleeuw.png",
    year: 2026,
    category: null,
    bio: null,
    featured: true,
  },
  {
    name: "Sean Hawley",
    slug: "sean-hawley",
    photo: "/inductees/sean-hawley.jpg",
    year: 2026,
    category: null,
    bio: null,
    featured: true,
  },
];

/** Helper to find an inductee by slug */
export function getInducteeBySlug(slug: string): Inductee | undefined {
  return inductees.find((i) => i.slug === slug);
}

/** Helper to get featured inductees */
export function getFeaturedInductees(): Inductee[] {
  return inductees.filter((i) => i.featured);
}
