export interface Inductee {
  name: string;
  slug: string;
  photo: string;
  year: number | null;
  category: "shooting" | "administrative" | "both" | null;
  bio: string | null;
  featured: boolean;
}

export const inductees: Inductee[] = [
  {
    name: "Hortense Wood",
    slug: "hortense-wood",
    photo: "/inductees/hortense-wood.jpg",
    year: 1986,
    category: "both",
    bio: "One of the most decorated female trapshooters in ATA history, Hortense Wood began her shooting career in Utah around 1940 and went on to claim 19 Utah women's state championships along with one doubles and one all-around title over the men. She was Ladies' Singles Champion 18 times, Doubles Open Champion in 1967, and HAA Open Champion in 1955. She placed on 24 women's ATA All-America teams — 20 of them first-team honors — and in 1970 became only the second woman in ATA history to be handicapped at 27 yards, the maximum distance. A trailblazer off the range as well, she served as president of the Salt Lake Gun Club from 1960 to 1962, becoming the first woman to head a major gun club in the country.",
    featured: false,
  },
  {
    name: "Pat Miller",
    slug: "pat-miller",
    photo: "/inductees/pat-miller.jpg",
    year: 1986,
    category: null,
    bio: "Pat Miller competed during the 1950s and 1960s and is recognized among the foundational figures of Utah trapshooting. He won three State Singles titles, two Doubles titles, one Handicap title, six HAA titles, and one HOA title in 1961. Pat was honored as one of the early inductees in the Utah Trapshooting Hall of Fame for sustained contributions to the sport and competition within the state.",
    featured: false,
  },
  {
    name: "Sam Sharman",
    slug: "sam-sharman",
    photo: "/inductees/sam-sharman.jpg",
    year: 1997,
    category: "shooting",
    bio: "Sam Sharman of Salt Lake City shot registered targets from 1922 to 1942 and served as the A.T.A. President in 1936 — the first President from Utah. Sam was the first person in Utah to win the Utah State Singles Championship with a 200×200 in 1929, a record held until 1960. He was the Utah State Singles Champion in 1922, 1923, 1926, 1929, 1931, 1932, and 1934, and also won the Utah Handicap, Doubles, and All Around Championships in 1926, 1931, 1932, 1934, 1935, and 1941. Sam swept all state titles in 1926, 1931, 1932, and 1934. He was a member of the 1931 All American Team and the 1924 Olympic Trap Team.",
    featured: false,
  },
  {
    name: "E.L. Ford",
    slug: "el-ford",
    photo: "/inductees/el-ford.jpg",
    year: 1997,
    category: "both",
    bio: "E.L. Ford of Ogden shot registered targets from 1917 to 1935 and served as President of the Utah State Association in 1920. He won the Singles, Handicap, and All Around Championships in 1921, the Singles Championship in 1924, 1925, 1927, and 1930, the Handicap Championship in 1922 and 1933, and the All Around Championship in 1925, 1927, 1930, and 1933.",
    featured: false,
  },
  {
    name: "C.H. Reilly",
    slug: "ch-reilly",
    photo: "/inductees/ch-reilly.jpg",
    year: 1997,
    category: "shooting",
    bio: "C.H. Reilly of Salt Lake City shot registered targets from 1913 to 1934, winning the Utah State Singles Championship in 1915, 1916, 1917, 1919, and 1920. He also won the Doubles Championship in 1922, 1923, 1924, 1927, and 1929.",
    featured: false,
  },
  {
    name: "Gus Becker",
    slug: "gus-becker",
    photo: "/inductees/gus-becker.jpg",
    year: 1997,
    category: "both",
    bio: "Gus Becker of Ogden shot registered targets from 1914 until 1942. He won the State Singles Title in 1918 and the Handicap Championship in 1918, 1934, and 1936. Gus won the Doubles Championship in 1920, 1921, 1925, 1932, 1933, 1934, and 1936, and also won the All Around Championship in 1936.",
    featured: false,
  },
  {
    name: "Ron Sellers",
    slug: "ron-sellers",
    photo: "/inductees/ron-sellers.jpg",
    year: 1997,
    category: "shooting",
    bio: "Ron Sellers of Bountiful has shot registered targets since 1959 and is still shooting. Ron was the first person to tie the record set by Sam Sharman in 1929 by shooting 200×200 to win the State Singles Championship, and also tied a record set by C.H. Reilly in 1929 to win the State Doubles Championship in 1971. He won the Singles Championship in 1960 and 1965, the Doubles Championship in 1969, 1971, 1973, 1974, and 1975, and the State All Around Championship in 1969, 1975, 1981, and 1983. Ron is the only person to break 100×100 from each full yardage marker from the 21 to the 27 in both ATA and PITA firing. He made the ATA All American Team from 1971 to 1975, with 1973 on the 2nd team and all others on the 1st team.",
    featured: false,
  },
  {
    name: "Arvin Labrum",
    slug: "arvin-labrum",
    photo: "/inductees/arvin-labrum.jpg",
    year: 1998,
    category: "shooting",
    bio: "Arvin G. Labrum (1932–2017) of the Uintah Basin competed from the early 1960s through 2000. He won the State Singles title once, Doubles four times, and HAA once. A dedicated and accomplished trapshooter, Labrum famously flew himself to competitions across the United States in his own Beechcraft Bonanza aircraft, piloting a course that combined his two great passions — the skies and the clay target field.",
    featured: false,
  },
  {
    name: "Ken Adamson",
    slug: "ken-adamson",
    photo: "/inductees/ken-adamson.jpg",
    year: 1998,
    category: null,
    bio: "Ken Adamson competed from the mid-1960s through 2000. He won the State Singles title six times, the HAA title four times, and the HOA title once. Ken is recognized as one of Utah's distinguished contributors to the sport of trapshooting, honored among the inductees of the Utah State Trapshooting Association's Hall of Fame for a career of sustained competitive excellence and commitment to the sport within the state.",
    featured: false,
  },
  {
    name: "Ann Christie",
    slug: "ann-christie",
    photo: "/inductees/ann-christie.jpg",
    year: 1998,
    category: null,
    bio: "Ann Christie was active in the early 1950s. She won the Open Handicap Championship in both 1951 and 1952, and also won the Ladies' Singles Title in those same two years. Ann is honored as a trailblazer in Utah trapshooting, recognized among the inductees of the Utah State Trapshooting Association's Hall of Fame for both competitive achievement and a meaningful contribution to the growth of the sport in Utah, particularly for women in the shooting sports community.",
    featured: false,
  },
  {
    name: "O.J. Coon",
    slug: "oj-coon",
    photo: "/inductees/oj-coon.jpg",
    year: 1998,
    category: null,
    bio: "O.J. Coon stands among the pioneer inductees of the Utah State Trapshooting Association's Hall of Fame, recognized for his early and lasting contributions to the sport of trapshooting in Utah. His place alongside the association's founding-era honorees reflects a role in establishing the competitive trapshooting tradition that continues in the state today.",
    featured: false,
  },
  {
    name: "Josephine Leavitt",
    slug: "josephine-leavitt",
    photo: "/inductees/josephine-leavitt.jpg",
    year: 1998,
    category: "shooting",
    bio: "Josephine \"Jody\" Leavitt Jorgensen (1927–2023) of Kaysville and later St. George, Utah, competed in the early 1960s and won the Ladies Singles title in 1962. A multi-sport competitor, she distinguished herself as an accomplished trapshooter alongside careers in bowling and golf. She earned numerous awards and accolades throughout her long life, and her competitive spirit and longevity in the sport made her an enduring example for women trapshooters across the state.",
    featured: false,
  },
  {
    name: "John M. Browning",
    slug: "john-browning",
    photo: "/inductees/john-browning.jpg",
    year: 1999,
    category: "both",
    bio: "John M. Browning of Morgan is being inducted for obvious reasons — the list of guns he invented during the last quarter of the 19th century and continuing through the first quarter of the 20th defies belief: the Model 1894 lever action rifle, the Model 1897 pump shotgun, the .22 caliber pump and single-shot rifles, as well as rifles, handguns (the Colt 45 is a Browning invention), machine guns, cannons, and antiaircraft guns for other arms companies and the U.S. military. In 1883 he was approached by Winchester Repeating Arms Company, and for the next 19 years designed guns for Winchester that made them the largest producer of sporting arms in the U.S. It was during this time that Browning designed the Auto-Five, the first gas-operated automatic shotgun. Since its invention in 1899, the Browning A-5 is still in production and to date has sold more than 1.25 million under the Fabrique name alone and untold tens of thousands under the name of Remington, Franchi, Beda, Save, and others.",
    featured: false,
  },
  {
    name: "Tom Lynott",
    slug: "tom-lynott",
    photo: "/inductees/tom-lynott.jpg",
    year: 1999,
    category: "shooting",
    bio: "Tom Lynott of Salt Lake City worked for Winchester Ammunition. He was second among pros in the Grand American Class Singles in 1954, tied in the Dayton Homecoming in 1956, and in 1958 was first among the pros in the Class Championship. In 1960 Tom won the Dayton Homecoming. He was on the Professional All American Team in 1949, 1951 through 1961, 1965, 1966, and 1967.",
    featured: false,
  },
  {
    name: "Walter Langhorst",
    slug: "walt-langhorst",
    photo: "/inductees/walt-langhorst.jpg",
    year: 1999,
    category: "shooting",
    bio: "Walter Langhorst of Salt Lake City was the district manager for Remington Arms Co. and began registering targets in 1954. That same year he won Professional Doubles honors at the Baby Grand in Elko, Nevada. He entered his first 100 straight in Phoenix five years later and earned the Professional prize in the 1962 Golden West Grand Doubles Championship. Mr. Langhorst was the Professional Runner-up in the 1965 Grand American Singles Class Championship and was the Grand American Professional Doubles and Clay Target Champion in 1968. Walt was named to the Professional All American Team each year from 1966 through 1969.",
    featured: false,
  },
  {
    name: "Dean Hurd",
    slug: "dean-hurd",
    photo: "/inductees/dean-hurd.jpg",
    year: 2000,
    category: null,
    bio: "Dean Hurd competed from 1936 to 1950. He won three State Singles titles, one Doubles title, and four HAA titles. Dean was a recognized competitor and contributor to Utah trapshooting who earned induction into the Utah State Trapshooting Association's Hall of Fame for his accomplishments in the sport.",
    featured: false,
  },
  {
    name: "Randy Freston",
    slug: "randy-freston",
    photo: "/inductees/randy-freston.jpg",
    year: 2000,
    category: "both",
    bio: "Born September 20, 1945, in Roosevelt, Utah, Randy Lynn Freston rose to the highest levels of the sport, serving as President of the Amateur Trapshooting Association in 1989 — a testament to both his world-class shooting ability and his commitment to the governance and growth of trapshooting nationally. A licensed civil engineer who owned his own firm for 35 years, Freston spent much of his later career giving back to the next generation through the Scholastic Clay Target Program, helping introduce young shooters to the discipline he loved. He passed away on March 19, 2015, at the age of 69.",
    featured: false,
  },
  {
    name: "H. Barr Carlisle",
    slug: "h-barr-carlisle",
    photo: "/inductees/h-barr-carlisle.jpg",
    year: 2001,
    category: null,
    bio: "H. Barr Carlisle of Salt Lake City won the Utah State Doubles Championship in 1936 and the Handicap Championship in 1942. Barr, as he was called, was State President of the PITA in 1936. He won the PITA Doubles Championship in 1939, 1940, 1941, 1950, and 1959, was the PITA Utah Handicap Champion in 1939, 1941, and 1950, as well as Utah PITA Singles Champion in 1955 and 1957 and the All Around Champion in 1941 and 1950.",
    featured: false,
  },
  {
    name: "Dale Amos",
    slug: "dale-amos",
    photo: "/inductees/dale-amos.jpg",
    year: 2001,
    category: "shooting",
    bio: "Dale Amos of Spanish Fork has been the Utah State All Around Champion eight times: 1978, 1979, 1984, 1986, 1987, 1989, 1992, and 1993. He won the State Singles Championship in 1980, 1986, 1989, and 1993, the Handicap Championship in 1992, 1993, and 2000, and the Doubles Championship in 1979, 1986, 1988, and 1992. Amos won AA 3rd for the Singles Championship at the 1980 Grand American and was a member of the 1986 Men's All American 2nd Team. Dale was the 2000 Western Zone Handicap Champion with 100 straight.",
    featured: false,
  },
  {
    name: "Ron Christensen",
    slug: "ron-christensen",
    photo: "/inductees/ron-christensen.jpg",
    year: 2001,
    category: "both",
    bio: "Ron Christensen of Goshen held the Utah State Doubles Championship in 1985 and 1994, the Singles Championship in 1991, and the Handicap Championship in 1996. He was the Utah State High All Around and High Over All Champion in 1989. Ron won AAA Doubles at the Grand American in 1997, the first year of the AAA class. He won the Western Grand Handicap Championship in 1995 and the Doubles Championship in 1988 and 1994, the Golden West Grand Doubles Championship in 1994 and 1998, and the High All Around trophy in 1994. He also won the 1986 Doubles Championship at the Spring Grand. Ron was a member of the Men's All American 2nd Team in 1986, 1990, 1992, 1997, and 1998. A past president of the Utah State Association, Ron was appointed to form the Utah Trapshooting Hall of Fame Committee in 1995, formally submitted the outline for approval in 1996, and conducted the first inductions in 1997.",
    featured: false,
  },
  {
    name: "Doug Westenskow",
    slug: "doug-westenskow",
    photo: "/inductees/doug-westenskow.jpg",
    year: 2002,
    category: "shooting",
    bio: "Douglas Westenskow of Salt Lake City won the Utah State Doubles Championship in 1958, 1962, and 1963 and was the Doubles Runnerup in 1970. Doug won the Utah State High Over All Trophy in 1959 and 1963. His lifetime target attainment is 31,910 for Singles, 32,825 for Handicap, and 17,150 for Doubles.",
    featured: false,
  },
  {
    name: "Brent Epperson",
    slug: "brent-epperson",
    photo: "/inductees/brent-epperson.jpg",
    year: 2004,
    category: "both",
    bio: "Brent Epperson of Centerville won the Utah State Handicap Championship in 2001 and 2002 and the Doubles Championship in 2003. Brent won the Utah State High All Around Trophy in 2000 and 2002. He also won 6 trophies at the Grand American as well as the Western Grand Handicap Championship in 2003 and the Western Zone Singles Championship in 2001. Mr. Epperson made the 2003 Men's All American First Team and the 2004 All American Second Team.",
    featured: false,
  },
  {
    name: "Bill Hunter",
    slug: "bill-hunter",
    photo: "/inductees/bill-hunter.jpg",
    year: 2004,
    category: "administrative",
    bio: "Bill Hunter of Carson, California is being inducted into the Utah Trapshooting Hall of Fame as an Honorary Member on his merits as a contributor and supporter of trapshooting worldwide. Whenever he sees a need, Bill has always tried to fill it — from supplying free doughnuts and coffee at gun clubs, to giving parties in honor of trap help, furnishing trophies and awards for shoots, or donating to the Trapshooting Hall of Fame or the Capital Improvement Fund. For many years, Mr. Hunter donated 100 life memberships per year to be given at every state and provincial shoot plus the Satellite Grands and the Grand American.",
    featured: false,
  },
  {
    name: "Jim Duke",
    slug: "jim-duke",
    photo: "/inductees/jim-duke.jpg",
    year: 2007,
    category: "both",
    bio: "Jimmy Ray Duke was the founding father of organized trapshooting in the Heber Valley, organizing some of the region's earliest informal shoots and playing a central role in establishing the Heber Valley Gun Club — an institution that endures to this day. A lifelong competitor, Duke registered more than 231,000 ATA targets across singles, handicap, and doubles, claiming Utah State titles in singles (1987) and handicap (1994) along with multiple veteran and senior veteran championships. In the words of those who honored him, \"without Jimmy, there would be no trapshooting in the Heber Valley.\" He continued competing into his nineties and passed away on June 30, 2022, leaving behind a community he helped build from the ground up.",
    featured: false,
  },
  {
    name: "Larry Mitchell",
    slug: "larry-mitchell",
    photo: "/inductees/larry-mitchell.jpg",
    year: 2009,
    category: null,
    bio: "Larry Mitchell managed the Salt Lake Gun Club for at least 30 years and played a key role in starting the Lee Kay Shotgun Center. He also founded the popular Utah State Round Robin Tournament. Larry owned several clay target companies, including Meteor. His wife Sheena and son Storm were also champion Utah trapshooters. Larry won the State Handicap title in 1990. His induction into the Utah Trapshooting Hall of Fame reflects a career and legacy deemed worthy of the sport's highest state honor.",
    featured: false,
  },
  {
    name: "Joe Sudbury Sr.",
    slug: "joe-sudbury-sr",
    photo: "/inductees/joe-sudbury-sr.jpg",
    year: 2012,
    category: "shooting",
    bio: "Active since the early 1980s, Joe Sudbury Sr. is one of Utah's most accomplished registered trapshooters, celebrated for a competitive career marked by consistency and longevity. His Open titles include Singles five times, Doubles once, HAA four times, and HOA six times, along with numerous Veteran and Senior Vet Singles, Doubles, Handicap, HAA, HOA, and several Zone titles and Satellite Grand titles. At the 2017 Utah State Shoot, he won the Singles Championship outright with a 200 straight, remarkably having broken all 500 singles targets across the entire week of competition. He continued to compete at the highest level into his senior veteran years, earning ATA Senior Veteran Second Team All-American honors. His dedication to registered competition over multiple decades makes him one of the most respected names in Utah trapshooting.",
    featured: false,
  },
  {
    name: "Linda Nicholl",
    slug: "linda-nicholl",
    photo: "/inductees/linda-nicholl.jpg",
    year: 2010,
    category: null,
    bio: "Linda Nicholl competed in the late 1970s and early 1980s. She won five Ladies' Singles titles and several Ladies' Handicap and Doubles titles. Linda was also a skilled skeet shooter. Her induction into the Utah Trapshooting Hall of Fame speaks to a career of sustained participation and achievement within the state's shooting community, contributing to the growth of women's competition in registered ATA events.",
    featured: false,
  },
  {
    name: "Joe Mabey",
    slug: "joe-mabey",
    photo: "/inductees/joe-mabey.jpg",
    year: 2010,
    category: null,
    bio: "Joe Mabey competed in the early 1950s and won the State Singles title once, Doubles three times, and HAA twice. He is enshrined in the Utah Trapshooting Hall of Fame in recognition of his contributions to the sport within the state, reflecting a legacy of dedication to the trapshooting community that the association deemed worthy of permanent recognition.",
    featured: false,
  },
  {
    name: "Bill Salt",
    slug: "bill-salt",
    photo: "/inductees/bill-salt.jpg",
    year: 2012,
    category: "shooting",
    bio: "Bill Salt earned his place among Utah's trapshooting elite through sustained excellence at the national level, earning selection to the ATA All-American Men's First Team in 1962 — a distinction that placed him among the finest registered competitors in the country. Bill also won the Utah State Doubles title in 1960. Competing during an era when Utah trapshooting was still building its stature on the national stage, Salt's achievement brought recognition to the state association and served as a benchmark for future generations of Utah shooters.",
    featured: false,
  },
  {
    name: "Bob Spencer",
    slug: "bob-spencer",
    photo: "/inductees/bob-spencer.jpg",
    year: 2013,
    category: null,
    bio: "Bob Spencer competed in the late 1980s and early 1990s. He won four Senior Vet Singles titles, as well as Handicap and Doubles events. Bob is a Hall of Fame inductee of the Utah State Trapshooting Association, recognized for his contributions to the state's trapshooting community through competition and service.",
    featured: false,
  },
  {
    name: "Gene Majers",
    slug: "gene-majers",
    photo: "/inductees/gene-majers.jpg",
    year: 2015,
    category: "shooting",
    bio: "Gene Majers is a Utah-based ATA competitor recognized for his performance in the veteran category of registered trapshooting and his longevity as a competitive shooter in the state. Gene won the State Singles title in 2008 and has also earned several Senior Vet Singles, Handicap, and Doubles titles. His induction into the Utah Trapshooting Hall of Fame honors a career of sustained dedication to the sport.",
    featured: false,
  },
  {
    name: "Stanley Jorgenson",
    slug: "stanley-jorgenson",
    photo: "/inductees/stanley-jorgenson.jpg",
    year: 2001,
    category: "shooting",
    bio: "Stanley Jorgenson of Salt Lake City started registering targets in 1964 and had his first 100 straight in singles in 1965. Stan won the Utah State High All Around in 1966 and 1967 and was also the High Over All Champion in 1966 as well as the A class Singles Champion. He was the PITA State Handicap Champion in 1965 as well as the 1966 PITA State Handicap Champion and All Around Champion. In 1966, Stan had the high average in singles, handicap, and doubles and repeated the accomplishment again in 1967 for singles and doubles.",
    featured: false,
  },
  {
    name: "Bill & LeeAnn Martin",
    slug: "bill-and-leeann-martin",
    photo: "/inductees/bill-and-leeann-martin.jpg",
    year: 2016,
    category: "both",
    bio: "Bill and LeeAnn Martin of Vernal, Utah took up the sport together in 1996, joining Bill's brother Pete and business partner Craig Hart at their home club, Vernal Rod & Gun Club, where they later helped expand the trapline to 13 fields and construct a new club building. A decorated competitor, Bill earned three Utah state titles (1997 singles, 2000 doubles, 2013 veteran), a Grand American singles trophy in 2007, and completed his ATA Grand Slam in 2005 after shooting over 357,000 registered targets across 21 states and Canada. The Martins are among the most generous benefactors in the history of the sport, contributing $1 million toward construction of the ATA Hall of Fame and Museum in Sparta, Illinois, and sponsoring multiple six-figure Grand American challenge events. Bill and LeeAnn were inducted into the ATA Hall of Fame in 2014 — the highest honor the sport can bestow. Bill passed away on May 26, 2025, at age 78 in Vernal, Utah.",
    featured: false,
  },
  {
    name: "Ardith Stitt",
    slug: "ardith-stitt",
    photo: "/inductees/ardith-stitt.jpg",
    year: 2019,
    category: "administrative",
    bio: "Ardith Stitt devoted more than two decades to building the future of Utah trapshooting through tireless work with its youth. Beginning around 2000 as a fundraiser for the SCTP program, she helped send as many as six squads per year to the Grand American, regularly producing top-10 national finishes, before becoming Utah's state coordinator for the ATA's AIM program. She is credited with successfully lobbying for trap shooting to be recognized as a high school letter sport in Utah — a landmark achievement for the state's young competitors. Over 18-plus years of service, Ardith shaped the competitive futures of countless Utah junior shooters.",
    featured: false,
  },
  {
    name: "Sharred Oaks",
    slug: "sharred-oaks",
    photo: "/inductees/sharred-oaks.jpg",
    year: 2019,
    category: "shooting",
    bio: "Sharred Oaks of Vernal, Utah is one of the most accomplished young trapshooters the state has ever produced, becoming the youngest inductee in the Utah Trapshooting Hall of Fame at just 19 years of age. A member of the Vernal Rod & Gun Club — the oldest private trapshooting club in Utah — Sharred posted a rare 100-straight in all three events at a single registered shoot and capped his ATA Grand Slam with a perfect 300×300 performance from the 27-yard line. He has won the Utah State Singles title two times, Doubles title four times, HAA two times, and HOA three times. At the 2017 Utah State Shoot he won both the all-around and high-over-all titles, and at the Grand American he claimed junior honors in the NRA Singles with a 200 and won the junior doubles championship with a perfect 100.",
    featured: false,
  },
  {
    name: "Joe Roach",
    slug: "joe-roach",
    photo: "/inductees/joe-roach.png",
    year: 2017,
    category: "shooting",
    bio: "Active from the 1980s through 2020, Joe has been a key figure in Utah shooting for many years. He has won the State Handicap Championship, Doubles, Open HAA, and Vet Singles each once, along with many Veteran doubles and handicap championships.",
    featured: false,
  },
  {
    name: "Leslie (Ford) Hight",
    slug: "leslie-ford-hight",
    photo: "/inductees/leslie-ford-hight.jpg",
    year: 2016,
    category: "shooting",
    bio: "Active since the early 2000s through the present, Leslie Ford Hight is a long-standing competitor in Utah's ATA trapshooting community, competing primarily through the Spanish Fork Gun Club. Leslie has won the Ladies State Singles title eight times, along with several Ladies handicap and doubles titles. She has been recognized for sustained performance in women's competition, reflecting decades of consistent competitive excellence at the registered level.",
    featured: false,
  },
  {
    name: "Pam Wright",
    slug: "pam-wright",
    photo: "/inductees/pam-wright.jpg",
    year: 2026,
    category: "shooting",
    bio: "Pam has won many Utah State Lady I and II Championships, as well as several Western Zone, Western Grand, and Grand American trophies. She has been a member of the Utah State Trap Shooting Association's Ladies Team for 15 straight years, from 2001 to 2025, serving as team captain for three of those years. Pam has been named to the ATA All-American Lady 2 First Team five years in a row, qualifying as an All-American Lady II Team member in 2025, 2024, 2023, 2022, and 2021. Pam got her start in trapshooting by practicing with her brother Doug Ford, some of the boys, and Leslie Hight. Doug remembers that he and Pam would shoot together from time to time before he slowed down. He says, \"She's a fierce competitor. When she sets her mind to something, she does it.\" He also adds, \"She's always willing to help with anything.\"",
    featured: true,
  },
  {
    name: "Pauline Deleeuw",
    slug: "pauline-deleeuw",
    photo: "/inductees/pauline-deleeuw.jpg",
    year: 2026,
    category: "both",
    bio: "Pauline is known for winning multiple High Lady singles titles at the Utah State Shoot. She is the only woman in the event's history, from 1914 to 2025, to shoot a perfect 200 in the singles championship. Her achievements include High Lady Handicap at the 1978 Utah State Shoot, Singles High Lady I in 1984, 1987, 1992, and 1995, and Handicap High Lady I in 1987. To date she is the only lady to run 200 straight in the Utah State singles championship. Pauline also served as Secretary of the Magna Gun Club, sat on its Board of Directors, and helped organize the first Utah Cancer \"Shoot Out\" at Lee Kay Shooting Complex. She made a significant voluntary contribution helping run Magna Gun Club from inception to closure. Pauline began shooting in 1975 and retired in 2000 due to health reasons. Even at 91, she would still love to be on the range. Over her 25-year career, she shot 22,000 singles, 18,200 handicap, and 1,700 doubles targets.",
    featured: true,
  },
  {
    name: "Sean Hawley",
    slug: "sean-hawley",
    photo: "/inductees/sean-hawley.jpg",
    year: 2026,
    category: "shooting",
    bio: "Sean has been a lifetime member of the ATA since joining in 1981 at age 12. His best singles average is 99.68%, his top handicap average is 96.52%, and his highest doubles average is 99.67%. Sean has won several Utah Championships: Singles once, Handicap twice, Doubles once, HOA six times, and HAA five times. He has also earned many Satellite Grand Championships and Grand American Trophies, including the coveted HOA ring at the Grand American. Sean has been named to the ATA All-American team 31 times: once as a sub-junior, three times as a junior, and 27 times on the First and Second Open Teams. He has been on the team for 19 straight years, from 2007 to 2025.",
    featured: true,
  },
];

/** Helper to find an inductee by slug */
export function getInducteeBySlug(slug: string): Inductee | undefined {
  return inductees.find((i) => i.slug === slug);
}

/** Helper to get featured inductees */
export function getFeaturedInductees(): Inductee[] {
  return inductees.filter((i) => i.featured);
}
